# Generated by Django 4.1 on 2022-09-07 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0002_remove_comidas_apto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebidas',
            name='apto',
        ),
    ]
